# Generated by Django 3.2.3 on 2021-09-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_alter_myemp_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myemp',
            name='dob',
        ),
    ]
