# Generated by Django 3.2.3 on 2021-09-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_remove_myemp_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myemp',
            name='doj',
            field=models.DateField(default='2021 Oct 30'),
        ),
    ]
