# Generated by Django 3.2.3 on 2021-09-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_alter_myemp_doj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myemp',
            name='doj',
            field=models.DateField(default='2021-10-30'),
        ),
    ]
