# Generated by Django 3.2.3 on 2021-10-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_alter_myemp_doj'),
    ]

    operations = [
        migrations.AddField(
            model_name='myemp',
            name='dob',
            field=models.DateField(default='1990-10-30'),
        ),
    ]
